In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/Chocolate Sales.csv")

In [3]:
df.head(10)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
5,Van Tuxwell,India,Smooth Sliky Salty,06/06/2022,"$5,376.00",38
6,Oby Sorrel,UK,99% Dark & Pure,25/01/2022,"$13,685.00",176
7,Gunar Cockshoot,Australia,After Nines,24/03/2022,"$3,080.00",73
8,Jehu Rudeforth,New Zealand,50% Dark Bites,20/04/2022,"$3,990.00",59
9,Brien Boise,Australia,99% Dark & Pure,04/07/2022,"$2,835.00",102

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB

In [5]:
df.columns

Index(['Sales Person', 'Country', 'Product', 'Date', 'Amount',
       'Boxes Shipped'],
      dtype='str')

In [6]:
df.describe()

       Boxes Shipped
count    3282.000000
mean      164.666971
std       124.024736
min         1.000000
25%        71.000000
50%       137.000000
75%       232.000000
max       778.000000

In [7]:
df.isnull()

      Sales Person  Country  Product   Date  Amount  Boxes Shipped
0            False    False    False  False   False          False
1            False    False    False  False   False          False
2            False    False    False  False   False          False
3            False    False    False  False   False          False
4            False    False    False  False   False          False
...            ...      ...      ...    ...     ...            ...
3277         False    False    False  False   False          False
3278         False    False    False  False   False          False
3279         False    False    False  False   False          False
3280         False    False    False  False   False          False
3281         False    False    False  False   False          False

[3282 rows x 6 columns]

In [8]:
df.isnull().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

In [9]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3277    False
3278    False
3279    False
3280    False
3281    False
Length: 3282, dtype: bool

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} valores únicos")

Sales Person: 25 valores únicos
Country: 6 valores únicos
Product: 22 valores únicos
Date: 504 valores únicos
Amount: 3013 valores únicos
Boxes Shipped: 507 valores únicos